"""Migrations must run forwards, backwards and forwards again, with no drift."""

import uuid
from collections.abc import Iterator

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, make_url, text

from tests.conftest import alembic_config


@pytest.fixture
def scratch_database_url(database_url: str) -> Iterator[str]:
    """A throwaway database, so up/down cycles cannot disturb the session schema."""
    name = f"migrations_{uuid.uuid4().hex}"
    admin = create_engine(database_url, isolation_level="AUTOCOMMIT")
    with admin.connect() as connection:
        connection.execute(text(f'CREATE DATABASE "{name}"'))
    try:
        scratch = make_url(database_url).set(database=name)
        yield scratch.render_as_string(hide_password=False)
    finally:
        with admin.connect() as connection:
            connection.execute(text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
        admin.dispose()


def test_upgrade_downgrade_upgrade(scratch_database_url: str) -> None:
    config = alembic_config(scratch_database_url)

    command.upgrade(config, "head")
    assert _citext_installed(scratch_database_url) is True

    command.downgrade(config, "base")
    assert _citext_installed(scratch_database_url) is False

    command.upgrade(config, "head")
    assert _citext_installed(scratch_database_url) is True


def test_alembic_check_reports_no_drift(scratch_database_url: str) -> None:
    config = alembic_config(scratch_database_url)
    command.upgrade(config, "head")

    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - only on real drift
        pytest.fail(f"models and migrations have drifted: {exc}")


def _citext_installed(url: str) -> bool:
    engine = create_engine(url)
    try:
        with engine.connect() as connection:
            result = connection.execute(
                text("SELECT 1 FROM pg_extension WHERE extname = 'citext'")
            )
            return result.scalar_one_or_none() is not None
    finally:
        engine.dispose()
